In [1]:
import torch

In [2]:
import torchaudio

In [6]:
a = torchaudio.info('/nvme/zhiyong/vox1/test/wav/id10270/5r0dWxy17C8/00001.wav')

In [8]:
print(a)

AudioMetaData(sample_rate=16000, num_frames=133761, num_channels=1, bits_per_sample=16, encoding=PCM_S)


In [17]:
a, b = torchaudio.backend.sox_io_backend.load('/nvme/zhiyong/vox1/test/wav/id10270/5r0dWxy17C8/00001.wav', normalize=False)

In [18]:
a

tensor([[-147, -137,  -86,  ...,  581, 1629, 2023]], dtype=torch.int16)

In [3]:
import scipy.io.wavfile as wavfile
sample_rate, audio  = wavfile.read('/nvme/zhiyong/vox1/test/wav/id10270/5r0dWxy17C8/00001.wav')

In [3]:
from src.SpeakerNet import SpeakerNet

In [4]:
s = SpeakerNet(model='X_vector', trainfunc='softmax', nPerSpeaker=1, Syncbatch=False, n_mels=40, nOut=192, spec_aug=False, nClasses=5994)

X_vector.py, Embedding size is 192,  Spec_aug False.
Initialised Softmax Loss


In [8]:
'__L__' in '__L__.fc.weight'

True

In [7]:
s.state_dict().keys()

odict_keys(['__S__.torchfb.0.flipped_filter', '__S__.torchfb.1.spectrogram.window', '__S__.torchfb.1.mel_scale.fb', '__S__.tdnn1.0.weight', '__S__.tdnn1.0.bias', '__S__.tdnn1.2.weight', '__S__.tdnn1.2.bias', '__S__.tdnn1.2.running_mean', '__S__.tdnn1.2.running_var', '__S__.tdnn1.2.num_batches_tracked', '__S__.tdnn2.0.weight', '__S__.tdnn2.0.bias', '__S__.tdnn2.2.weight', '__S__.tdnn2.2.bias', '__S__.tdnn2.2.running_mean', '__S__.tdnn2.2.running_var', '__S__.tdnn2.2.num_batches_tracked', '__S__.tdnn3.0.weight', '__S__.tdnn3.0.bias', '__S__.tdnn3.2.weight', '__S__.tdnn3.2.bias', '__S__.tdnn3.2.running_mean', '__S__.tdnn3.2.running_var', '__S__.tdnn3.2.num_batches_tracked', '__S__.tdnn4.0.weight', '__S__.tdnn4.0.bias', '__S__.tdnn4.2.weight', '__S__.tdnn4.2.bias', '__S__.tdnn4.2.running_mean', '__S__.tdnn4.2.running_var', '__S__.tdnn4.2.num_batches_tracked', '__S__.tdnn5.0.weight', '__S__.tdnn5.0.bias', '__S__.tdnn5.2.weight', '__S__.tdnn5.2.bias', '__S__.tdnn5.2.running_mean', '__S__.tdn

In [3]:
s.state_dict()

OrderedDict([('__S__.torchfb.0.flipped_filter',
              tensor([[[-0.9700,  1.0000]]])),
             ('__S__.torchfb.1.spectrogram.window',
              tensor([0.0800, 0.0801, 0.0802, 0.0805, 0.0809, 0.0814, 0.0820, 0.0828, 0.0836,
                      0.0846, 0.0857, 0.0868, 0.0881, 0.0896, 0.0911, 0.0927, 0.0945, 0.0963,
                      0.0983, 0.1003, 0.1025, 0.1048, 0.1072, 0.1097, 0.1123, 0.1150, 0.1178,
                      0.1208, 0.1238, 0.1269, 0.1301, 0.1335, 0.1369, 0.1404, 0.1441, 0.1478,
                      0.1516, 0.1555, 0.1595, 0.1637, 0.1679, 0.1721, 0.1765, 0.1810, 0.1856,
                      0.1902, 0.1949, 0.1998, 0.2047, 0.2097, 0.2147, 0.2199, 0.2251, 0.2304,
                      0.2358, 0.2413, 0.2468, 0.2524, 0.2581, 0.2638, 0.2696, 0.2755, 0.2814,
                      0.2874, 0.2935, 0.2997, 0.3058, 0.3121, 0.3184, 0.3248, 0.3312, 0.3376,
                      0.3441, 0.3507, 0.3573, 0.3640, 0.3707, 0.3774, 0.3842, 0.3910, 0.3979,
       

In [4]:
from src.DatasetLoader import get_data_loader

In [10]:
train_loader = get_data_loader(dataset_file_name='/nvme/zhiyong/sdsv21/vox2_trainlist.txt', batch_size=128, augment=False, musan_path='/nvme/zhiyong/musan_split', rir_path='/nvme/zhiyong/RIRS_NOISES/simulated_rirs', max_frames=300, max_seg_per_spk=10, nDataLoaderThread=4, nPerSpeaker=1, train_path='/nvme/zhiyong/sdsv21', sox_aug=False)

In [11]:
a = iter(train_loader)

In [12]:
len(a)

468

In [13]:
5994*10/128

468.28125

In [1]:
import glob

In [4]:
a = glob.glob('/nvme/zhiyong/CN-Celeb/data/*')

In [9]:
c = []
for i in a:
    b = glob.glob(i+'/*')
    if b[0].split('/')[-1].split('-')[0] == 'interview':
        c.append(i)

In [11]:
len(c)

362

In [5]:
path = '/nvme1/zhiyong/ASV_LOGS_202102/train_logs_201120/xvector(vox2)/model/model000000134.model'
# loaded_state = torch.load(path, map_location="cuda:0")

In [13]:
s.state_dict().keys()

odict_keys(['__S__.torchfb.0.flipped_filter', '__S__.torchfb.1.spectrogram.window', '__S__.torchfb.1.mel_scale.fb', '__S__.tdnn1.0.weight', '__S__.tdnn1.0.bias', '__S__.tdnn1.2.weight', '__S__.tdnn1.2.bias', '__S__.tdnn1.2.running_mean', '__S__.tdnn1.2.running_var', '__S__.tdnn1.2.num_batches_tracked', '__S__.tdnn2.0.weight', '__S__.tdnn2.0.bias', '__S__.tdnn2.2.weight', '__S__.tdnn2.2.bias', '__S__.tdnn2.2.running_mean', '__S__.tdnn2.2.running_var', '__S__.tdnn2.2.num_batches_tracked', '__S__.tdnn3.0.weight', '__S__.tdnn3.0.bias', '__S__.tdnn3.2.weight', '__S__.tdnn3.2.bias', '__S__.tdnn3.2.running_mean', '__S__.tdnn3.2.running_var', '__S__.tdnn3.2.num_batches_tracked', '__S__.tdnn4.0.weight', '__S__.tdnn4.0.bias', '__S__.tdnn4.2.weight', '__S__.tdnn4.2.bias', '__S__.tdnn4.2.running_mean', '__S__.tdnn4.2.running_var', '__S__.tdnn4.2.num_batches_tracked', '__S__.tdnn5.0.weight', '__S__.tdnn5.0.bias', '__S__.tdnn5.2.weight', '__S__.tdnn5.2.bias', '__S__.tdnn5.2.running_mean', '__S__.tdn

In [12]:
loaded_state['model'].keys()

odict_keys(['__S__.torchfb.0.flipped_filter', '__S__.torchfb.1.spectrogram.window', '__S__.torchfb.1.mel_scale.fb', '__S__.tdnn1.0.weight', '__S__.tdnn1.0.bias', '__S__.tdnn1.2.weight', '__S__.tdnn1.2.bias', '__S__.tdnn1.2.running_mean', '__S__.tdnn1.2.running_var', '__S__.tdnn1.2.num_batches_tracked', '__S__.tdnn2.0.weight', '__S__.tdnn2.0.bias', '__S__.tdnn2.2.weight', '__S__.tdnn2.2.bias', '__S__.tdnn2.2.running_mean', '__S__.tdnn2.2.running_var', '__S__.tdnn2.2.num_batches_tracked', '__S__.tdnn3.0.weight', '__S__.tdnn3.0.bias', '__S__.tdnn3.2.weight', '__S__.tdnn3.2.bias', '__S__.tdnn3.2.running_mean', '__S__.tdnn3.2.running_var', '__S__.tdnn3.2.num_batches_tracked', '__S__.tdnn4.0.weight', '__S__.tdnn4.0.bias', '__S__.tdnn4.2.weight', '__S__.tdnn4.2.bias', '__S__.tdnn4.2.running_mean', '__S__.tdnn4.2.running_var', '__S__.tdnn4.2.num_batches_tracked', '__S__.tdnn5.0.weight', '__S__.tdnn5.0.bias', '__S__.tdnn5.2.weight', '__S__.tdnn5.2.bias', '__S__.tdnn5.2.running_mean', '__S__.tdn

In [6]:
def loadParameters(model, path, map_location="cuda:0"):

    self_state = model.state_dict()
    loaded_state = torch.load(path, map_location=map_location)

    for name, param in loaded_state['model'].items():
        if name == '__L__.W':
            continue
        
        origname = name
        if name not in self_state:
            name = name.replace("module.", "")
            if name not in self_state:
                name = "__S__."+name
                if name not in self_state:
                    print("#%s is not in the model."%origname)
                    continue

        if self_state[name].size() != loaded_state['model'][origname].size():
            print("#Wrong parameter length: %s, model: %s, loaded: %s"%(origname, self_state[name].size(), loaded_state['model'][origname].size()))
            continue

        self_state[name].copy_(param)


In [7]:
loadParameters(s, path, 'cuda:0')

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy, math, pdb, sys, random
import time, os, itertools, shutil, importlib

from src.DatasetLoader import loadWAV
from src.tuneThreshold import tuneThresholdfromScore_std

def evaluateFromList(model, listfilename, distance_m='cosine', print_interval=100, test_path='', num_eval=10, eval_frames=0, verbose=True):
    assert distance_m in ['L2', 'cosine']
    if verbose:
        print('Distance metric: %s'%(distance_m))
        print('Evaluating from trial file: %s'%(listfilename))
    
    model = model.cuda()

    model.eval()
    
    lines       = []
    files       = []
    feats       = {}
    tstart      = time.time()

    ## Read all lines
    with open(listfilename) as listfile:
        while True:
            line = listfile.readline()
            if (not line):
                break

            data = line.split()

            ## Append random label if missing
            if len(data) == 2: data = [random.randint(0,1)] + data

            files.append(data[1])
            files.append(data[2])
            lines.append(line)

    setfiles = list(set(files))
    setfiles.sort()

    ## Save all features to file
    for idx, file in enumerate(setfiles):

        inp1 = torch.FloatTensor(loadWAV(os.path.join(test_path,file), eval_frames, evalmode=True, num_eval=num_eval)).cuda()

        ref_feat = model.forward(inp1).detach().cpu()

        filename = '%06d.wav'%idx

        feats[file] = ref_feat

        telapsed = time.time() - tstart

        if (idx % print_interval == 0) and verbose:
            sys.stdout.write("\rReading %d of %d: %.2f Hz, embedding size %d"%(idx, len(setfiles), idx/telapsed, ref_feat.size()[1]))

    all_scores = []
    all_labels = []
    all_trials = []
    tstart = time.time()

    ## Read files and compute all scores
    for idx, line in enumerate(lines):

        data = line.split()

        ## Append random label if missing
        if len(data) == 2: data = [random.randint(0,1)] + data


        ref_feat = feats[data[1]]
        com_feat = feats[data[2]]
        # ref_feat = (feats[data[1]] - mean_vector).cuda() 
        # com_feat = (feats[data[2]] - mean_vector).cuda()

        # if self.__model__.module.__L__.test_normalize:
        ref_feat = F.normalize(ref_feat, p=2, dim=1)
        com_feat = F.normalize(com_feat, p=2, dim=1)

        if distance_m == 'L2':
            dist = F.pairwise_distance(ref_feat.unsqueeze(-1), com_feat.unsqueeze(-1).transpose(0,2)).numpy()
            score = -1 * numpy.mean(dist)
        elif distance_m == 'cosine':
            ## [1, emb_size]
            dist = F.cosine_similarity(ref_feat.unsqueeze(-1), com_feat.unsqueeze(-1).transpose(0,2)).numpy()
            score = numpy.mean(dist)
        else:
            raise ValueError('Unknown distance metric: %s'%(distance_m))

        all_scores.append(score)
        all_labels.append(int(data[0]))
        all_trials.append(data[1]+" "+data[2])

        if (idx % (print_interval*100) == 0) and verbose:
            telapsed = time.time() - tstart
            sys.stdout.write("\rComputing %d of %d: %.2f Hz"%(idx,len(lines),idx/telapsed))
            sys.stdout.flush()

    result = tuneThresholdfromScore_std(all_scores, all_labels)
    print('')
    print('EER %2.4f MINC@0.01 %.5f MINC@0.001 %.5f'%(result[1], result[-2], result[-1]))

In [9]:
evaluateFromList(s, '/nvme/zhiyong/sdsv21/vox_o_triallist.txt', distance_m='cosine', print_interval=100, test_path='/nvme/zhiyong/sdsv21', num_eval=10, eval_frames=0, verbose=True)

Distance metric: cosine
Evaluating from trial file: /nvme/zhiyong/sdsv21/vox_o_triallist.txt
Computing 30000 of 37611: 6605.29 Hzedding size 192
EER 2.0469 MINC@0.01 0.23119 MINC@0.001 0.32961


In [3]:
import yaml
with open('/workspace/Federated-Averaging-PyTorch1/config.yaml') as c:
    configs = list(yaml.load_all(c, Loader=yaml.FullLoader))

In [4]:
configs

[{'global_config': {'seed': 5959,
   'device': 'cuda',
   'is_mp': False,
   'evaluate': True}},
 {'data_config': {'data_path': './data/',
   'dataset_name': 'MNIST',
   'num_shards': 200,
   'iid': False,
   'fl_dataset_path': '/workspace/flearn_data'}},
 {'fed_config': {'C': 0.6,
   'K': 12,
   'R': 500,
   'E': 1,
   'B': 10,
   'criterion': 'torch.nn.CrossEntropyLoss',
   'optimizer': 'torch.optim.SGD'}},
 {'optim_config': {'lr': 0.01, 'momentum': 0.9}},
 {'init_config': {'init_type': 'xavier',
   'init_gain': 1.0,
   'gpu_ids': [0, 1, 2]}},
 {'model_config': {'name': 'CNN',
   'in_channels': 1,
   'hidden_channels': 32,
   'num_hiddens': 512,
   'num_classes': 10}},
 {'log_config': {'log_path': './log/',
   'log_name': 'FL.log',
   'tb_port': 5252,
   'tb_host': '0.0.0.0'}},
 {'eval_config': {'eval_task': 'ver',
   'testfile_path': '/workspace/flearn_data',
   'model_path': '/nvme1/zhiyong/ASV_LOGS_202102/train_logs_201120/xvector(vox2)/model/model000000134.model',
   'listfilenam

In [6]:
global_config = configs[0]["global_config"]
data_config = configs[1]["data_config"]
fed_config = configs[2]["fed_config"]
optim_config = configs[3]["optim_config"]
init_config = configs[4]["init_config"]
model_config = configs[5]["model_config"]
log_config = configs[6]["log_config"]
eval_config = configs[7]["eval_config"]

In [9]:
import os
[os.path.join(data_config["fl_dataset_path"],
        "train_list_G%d.txt"%(i+1)) for i in range(fed_config["K"])]

['/workspace/flearn_data/train_list_G1.txt',
 '/workspace/flearn_data/train_list_G2.txt',
 '/workspace/flearn_data/train_list_G3.txt',
 '/workspace/flearn_data/train_list_G4.txt',
 '/workspace/flearn_data/train_list_G5.txt',
 '/workspace/flearn_data/train_list_G6.txt',
 '/workspace/flearn_data/train_list_G7.txt',
 '/workspace/flearn_data/train_list_G8.txt',
 '/workspace/flearn_data/train_list_G9.txt',
 '/workspace/flearn_data/train_list_G10.txt',
 '/workspace/flearn_data/train_list_G11.txt',
 '/workspace/flearn_data/train_list_G12.txt']

In [7]:
[data_config["fl_dataset_path"]] * fed_config["K"]

['/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data',
 '/workspace/flearn_data']

In [3]:
[ "train_list_G%d"%(i+1) for i in range(12) ]

['train_list_G1',
 'train_list_G2',
 'train_list_G3',
 'train_list_G4',
 'train_list_G5',
 'train_list_G6',
 'train_list_G7',
 'train_list_G8',
 'train_list_G9',
 'train_list_G10',
 'train_list_G11',
 'train_list_G12']

In [1]:
from src.DatasetLoader import get_data_loader_speaker

In [9]:
dataloader = get_data_loader_speaker(0*100, dataset_file_name="/workspace/flearn_data/train_list_G1.txt", 
    batch_size=128, augment=False, musan_path='/nvme/zhiyong/musan_split', 
    rir_path='/nvme/zhiyong/RIRS_NOISES/simulated_rirs', max_frames=300, 
    max_seg_per_spk=100, nDataLoaderThread=8, nPerSpeaker=1, 
    train_path='', sox_aug=False)

In [10]:
a = iter(dataloader)

In [13]:
next(a)

[tensor([[[ 3.9600e+02,  2.3000e+02, -1.1510e+03,  ...,  5.6200e+03,
           -3.8400e+02,  3.0000e+00]],
 
         [[-2.4550e+03, -3.1140e+03, -2.6730e+03,  ...,  2.6920e+03,
            2.8260e+03,  3.1890e+03]],
 
         [[-7.8600e+02,  1.9000e+02, -5.1000e+01,  ...,  4.0100e+02,
           -1.1490e+03, -2.1810e+03]],
 
         ...,
 
         [[-5.0680e+03, -4.0730e+03, -2.8300e+03,  ..., -7.7300e+02,
            5.2100e+02,  1.2240e+03]],
 
         [[-6.8700e+02,  9.7100e+02, -4.9100e+02,  ...,  1.0420e+03,
           -7.4200e+02,  4.3700e+02]],
 
         [[ 1.0600e+02,  1.2000e+02,  1.4000e+02,  ...,  1.8800e+02,
            1.1100e+02,  5.0000e+01]]]),
 tensor([85,  8, 87, 74, 84, 59, 27, 34, 74,  0, 37, 59, 33, 71, 14,  3, 72, 92,
         57, 32, 39, 77, 37, 18, 51,  8, 54, 36, 52, 23,  7, 10, 34,  3, 20, 84,
         59, 49, 61, 46, 84, 54,  4, 84, 60, 14, 15, 55, 63, 52, 27, 72, 15, 26,
         38, 85, 33, 68, 35,  3, 82, 97, 85, 99, 36, 71, 26, 51, 59,  3,  3, 13,
